### ISSUE TITLE
An Additional Ad Position

### ISSUE THREAD

**Issue by shaneedwards** [dovydaskukalis/nodebb-plugin-google-adsense#1]
Love your plugin, works perfectly right out of the box!  I would like to make a feature request for another ad position though.  

Please consider adding a location directly UNDER the first post in a topic (likely under the thread tools bar).  I feel like having the option to place it there would be a little less obtrusive than putting it inside the top post which may detract somewhat from the posts value.

This would also give us another place to use a banner ad rather than top/bottom of the screen.

Thanks!

**Comment by dovydaskukalis** [comment]
Hi, I will look at it this week

**Comment by shaneedwards** [comment]
Thank you very much!  I am letting my community grow for another week or two before I enable the ads, so I'll be patient!

**Comment by dovydaskukalis** [comment]
Hello, added ad after first post feature. Didn't have any time to test it fully, because I am getting ready to go on holidays to Croatia for a week. After I come back, I will test it more carefully or you can submit bug reports here.

**Comment by shaneedwards** [comment]
Hi, and thanks so much for working this in for me!  I just got it updated and went to load that section, but unfortunately I am running into some errors--here is a screen cap:

![image](https://cloud.githubusercontent.com/assets/7059852/3805077/6cd42332-1c30-11e4-93d2-ee910b24b6d2.png)

**Comment by dovydaskukalis** [comment]
Hello, just came back. Does it still happens? If so, tomorrow I will look at it.

**Comment by shaneedwards** [comment]
Yes, it was still happening when last I looked at it.  I ended up bringing the app version back down to a working version so that I could put some ads on the site for the time being.

**Comment by dovydaskukalis** [comment]
Plugin has been updated.
