### ISSUE TITLE
0.7.0 Google Ads

### ISSUE THREAD

**Issue by mastacontrola** [dovydaskukalis/nodebb-plugin-google-adsense#7]
NodeBB 0.7.0 and this plugin seem not to work.  We've added our api key and data, but nothing displays.  Attempting the full html output as a widget does seem to work.  I don't know where to begin looking to attempt fixing or seeing where the issue is.

**Comment by aggied** [comment]
bump here -- I can't get this plugin to do much of anything for me. I imagine there's many folks who are needing a solution like this one. Everyone has to keep the lights on...

**Comment by ngsankar** [comment]
i need this too..

**Comment by dovydaskukalis** [comment]
Plugin has been updated.

**Comment by aggied** [comment]
thanks -- ill update soon
