### ISSUE TITLE
Header ads need to be centered

### ISSUE THREAD

**Issue by singhnsk** [dovydaskukalis/nodebb-plugin-google-adsense#8]
Hello

The advertisement placed in the header is a bit off position and needs to be centered in order to look good. It is ugly in its current implementation :(

![2015-11-21_16-38-15](https://cloud.githubusercontent.com/assets/5565338/11318223/5228a126-906e-11e5-9ae1-f0f03c80f425.jpg)

**Comment by singhnsk** [comment]
Text ads go even farther to the edge of the page :|
![2015-11-21_16-44-45](https://cloud.githubusercontent.com/assets/5565338/11318238/4883271c-906f-11e5-8fce-f81ebc7bc1c5.jpg)

**Comment by schmittjoseph** [comment]
We have the same issue after upgrading to 0.0.12
